# Base16 Default Dark 256 - wezterm color config
[colors]
foreground = "#d8d8d8"
background = '#111111'
# background = "#181818"
# cursor_bg = "#d8d8d8"
# cursor_border = "#d8d8d8"
# cursor_fg = "#181818"
# selection_bg = "#dc3232"
# selection_fg = "#f8f8f8"

ansi = ['#181818', '#ab4642', '#a1b56c', '#f7ca88', '#7cafc2', '#ba8baf', '#86c1b9', '#d8d8d8']
brights = ['#585858', '#ab4642', '#a1b56c', '#f7ca88', '#7cafc2', '#ba8baf', '#86c1b9', '#f8f8f8']
