# Vague for WezTerm
# -------------------
# Theme Author: vague2k
# Ported by:    zukuo
# License:      MIT License

[colors]
foreground = "#cdcdcd"
background = "#141415"

cursor_bg = "#cdcdcd"
cursor_fg = "#cdcdcd"
cursor_border = "#cdcdcd"

selection_fg = "#cdcdcd"
selection_bg = "#252530"

scrollbar_thumb = "#606079"
split = "#252530"

ansi = [
  "#252530",
  "#d8647e",
  "#7fa563",
  "#f3be7c",
  "#6e94b2",
  "#bb9dbd",
  "#aeaed1",
  "#cdcdcd",
]

brights = [
  "#606079",
  "#e08398",
  "#99b782",
  "#f5cb96",
  "#8ba9c1",
  "#c9b1ca",
  "#bebeda",
  "#d7d7d7",
]

[colors.tab_bar]
background = "#141415"

[colors.tab_bar.active_tab]
bg_color = "#141415"
fg_color = "#cdcdcd"

[colors.tab_bar.inactive_tab]
bg_color = "#252530"
fg_color = "#606079"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#252530"
fg_color = "#bebeda"

[colors.tab_bar.new_tab]
bg_color = "#252530"
fg_color = "#606079"

[colors.tab_bar.new_tab_hover]
bg_color = "#252530"
fg_color = "#bebeda"
