# Zukuo's Custom Starship Prompt
# Modified Source: ChrisTitus - Bash Github

format = """
[](first)\
$username\
[](bg:second fg:first)\
$directory\
[](fg:second bg:third)\
$git_branch\
[](fg:third bg:fourth)\
$git_status\
[](fg:fourth bg:#fourth) \
"""
command_timeout = 5000
add_newline = true
palette = "colors"

[palettes.colors]
first = "#353535"
ffg = "#A1B56C" # first fg (green)
second = "#4A4A4A"
gfg = "black" # git fg
third = "#A1B56C"
fourth = "#FFC34A"

[username]
show_always = true
style_user = "fg:ffg bg:first"
style_root = "fg:ffg bg:first"
format = '[$user ]($style)'

[directory]
style = "fg:ffg bg:second"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false

# Move powerline symbols into the format bit to make git symbols only appear in git repo
[git_branch]
symbol = ""
style = "fg:gfg bg:third"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:gfg bg:fourth"
format = '[ $all_status$ahead_behind ]($style)'
